// examples/sveltekit-better-auth/src/routes/DispatchBadge.svelte
<script lang="ts">
import type { DispatchResult } from "$lib/server/cloud-ingest";
import Badge from "$lib/veritio-ui/Badge.svelte";

/**
 * Honest dispatch status pill: dispatched (emerald --success), failed
 * (warning), or local-only (muted). Re-authored from the React example's
 * `DispatchBadge`; it never claims delivery the server did not report.
 */
let { dispatch }: { dispatch: DispatchResult } = $props();
</script>

{#if dispatch.status === "dispatched"}
  <Badge variant="success" class="text-[10px]">Dispatched to Cloud</Badge>
{:else if dispatch.status === "failed"}
  <Badge variant="warning" class="text-[10px]">Dispatch failed · retrying</Badge>
{:else}
  <Badge variant="muted" class="text-[10px]">Captured locally</Badge>
{/if}

// examples/nextjs-better-auth/app/_components/dispatch-badge.tsx
import { Badge } from "../../src/veritio-ui/react/badge";
import type { DispatchResult } from "../../src/server/cloud-ingest";

/**
 * Honest dispatch status pill, shared by the change feed (server) and the entry
 * card's last-result banner (client). It has no client hooks, so it renders in
 * either context: dispatched (emerald --success), failed/retrying (warning), or
 * captured locally (muted) when the cloud is not configured.
 */
export function DispatchBadge({ dispatch }: Readonly<{ dispatch: DispatchResult }>) {
  if (dispatch.status === "dispatched") {
    return (
      <Badge variant="success" className="text-[10px]">
        Dispatched to Cloud
      </Badge>
    );
  }
  if (dispatch.status === "failed") {
    return (
      <Badge variant="warning" className="text-[10px]">
        Dispatch failed · retrying
      </Badge>
    );
  }
  return (
    <Badge variant="muted" className="text-[10px]">
      Captured locally
    </Badge>
  );
}
