// examples/vue-better-auth/src/veritio-ui/CardContent.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "./utils";

/**
 * Card body region, re-authored as a Vue SFC against the SAME class string as
 * the shared design kit's `react/card.tsx` CardContent (no top padding; pairs
 * with CardHeader's inset).
 */
const props = defineProps<{ class?: string }>();

const classes = computed(() => cn("px-5 pb-5", props.class));
</script>

<template>
  <div data-slot="card-content" :class="classes">
    <slot />
  </div>
</template>

// examples/sveltekit-better-auth/src/lib/veritio-ui/CardContent.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import type { HTMLAttributes } from "svelte/elements";
import { cn } from "./cn";

/**
 * Card body region (no top padding; pairs with CardHeader's inset). Mirrors the
 * React design kit's CardContent class string.
 */
type Props = { class?: string; children?: Snippet } & Omit<HTMLAttributes<HTMLDivElement>, "class">;
let { class: className = "", children, ...rest }: Props = $props();
</script>

<div data-slot="card-content" class={cn("px-5 pb-5", className)} {...rest}>
  {@render children?.()}
</div>
