// examples/tanstack-start-better-auth/src/routes/index.tsx
import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute()({
  component: Home,
});

function Home() {
  const [status, setStatus] = useState("idle");

  async function loadAuditTrail() {
    setStatus("loading");
    const response = await fetch("/api/audit");
    setStatus(response.ok ? "loaded" : "failed");
  }

  return (
    <main>
      <h1>Veritio Audit Trail</h1>
      <button type="button" onClick={loadAuditTrail}>
        Load reference audit trail
      </button>
      <p>{status}</p>
    </main>
  );
}

// examples/sveltekit-better-auth/src/routes/+page.svelte
<script lang="ts">
  let status = "idle";

  async function loadAuditTrail() {
    status = "loading";
    const response = await fetch("/api/audit");
    status = response.ok ? "loaded" : "failed";
  }
</script>

<main>
  <h1>Veritio Audit Trail</h1>
  <button type="button" on:click={loadAuditTrail}>Load reference audit trail</button>
  <p>{status}</p>
</main>
